# Generated by Django 5.1.2 on 2024-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_alter_client_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="contact",
        ),
        migrations.AddField(
            model_name="client",
            name="contact",
            field=models.ManyToManyField(related_name="clients", to="demo.contact"),
        ),
    ]
