# Generated by Django 5.1.2 on 2024-10-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_remove_client_contact_client_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="client",
            field=models.ManyToManyField(related_name="contacts", to="demo.client"),
        ),
    ]
