# Generated by Django 5.1.2 on 2024-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0004_remove_client_contact_contact_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=6,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
